config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  controller :session do
    get 'login', to: 'sessions#new' # or => :new
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
  root 'root#index', as: 'root_index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

require 'bcrypt'
class User < ApplicationRecord
  include BCrypt

  def self.find_by_login(login_handle)
    User.find_by(handle: login_handle)
  end

  def self.authenticate(user, password)
    pw = BCrypt::Engine.hash_secret(password, user.salt)
    user.update!(failed_login_attempts: 0) if pw == user.password
    pw == user.password
  end

  def failed_login
    increment!(:failed_login_attempts)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authorize_user
  def index; end

  protected

  def authorize_user
    return if session[:user_id] && User.find_by(id: session[:user_id])

    redirect_to login_path, notice: 'you must be logged in'
  end
end

app/controllers/root_controller.rb
# frozen_string_literal: true

class RootController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authorize_user, only: %i[new create]
  before_action :only_unauthorised, only: %i[new create]

  def new; end

  def create
    user = User.find_by_login(params[:name])
    if user.nil?
      flash.now.alert = 'login is invalid'
      render 'new'

    else
      check_user_authentication(user)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: 'Logged out'
  end

  protected

  def only_unauthorised
    return unless session[:user_id] && User.find_by(id: session[:user_id])

    redirect_to root_index_path,
                notice: 'already logged in'
  end

  def check_user_authentication(user)
    if user.failed_login_attempts >= 3
      flash.now.alert = 'User has been blocked from logging in'
      render 'new'
      return
    end
    if User.authenticate(user, params[:password])
      session[:user_id] = user.id
      redirect_to root_index_path, notice: 'logged in! YAY'
    else
      user.failed_login
      flash.now.alert = 'password is invalid'
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/session_helper.rb
# frozen_string_literal: true

module SessionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestLoginApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>

      <div class="flash-<%=type%>">
        <%= msg %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
      <br>
    </div>
  </body>
</html>

app/views/root/index.html.erb
<br>
<br>

<div class="logout">
  <br>
  <div class="logout_button">
    <%= link_to 'Log out', logout_url, method: :delete, id: "logout", data: { confirm: 'Are you sure?' } %></td>
  </div>
<div>